doctrine:
    dbal:
        dbname: "%env(resolve:APP_DATABASE_DB)%"
        user: "%env(resolve:APP_DATABASE_USER)%"
        password: "%env(resolve:APP_DATABASE_PASS)%"
        host: "%env(resolve:APP_DATABASE_HOST)%"
        port: "%env(resolve:APP_DATABASE_PORT)%"
        driver: pdo_mysql
        wrapper_class: \Doctrine\DBAL\Connection
        charset: utf8mb4
        mapping_types:
          enum: string
        default_table_options:
          charset: utf8mb4
          collate: utf8mb4_general_ci
          engine: InnoDB

        use_savepoints: true
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
